# Generated by Django 4.2.9 on 2024-07-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='uploads/products/'),
        ),
    ]
