# Generated by Django 4.2.9 on 2024-07-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customer_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='saved_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='saved_phone',
        ),
    ]
