# Generated by Django 4.2.9 on 2024-07-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_address_customer_saved_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='saved_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='saved_address',
        ),
    ]
