# Generated by Django 4.2.9 on 2024-07-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
