# Generated by Django 4.2.9 on 2024-07-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_customer_reward_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reward_points',
        ),
    ]
