# Generated by Django 4.0.6 on 2024-08-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_customer_reward_points'),
        ('store', '0017_customer_reward_points'),
    ]

    operations = [
    ]
