# Generated by Django 4.0.6 on 2024-08-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_productattribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
