# Generated by Django 4.0.6 on 2024-08-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_delete_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
