# Generated by Django 4.0.6 on 2024-08-11 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_productattribute_product_productattributekey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributekey',
            name='product',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.products'),
        ),
        migrations.CreateModel(
            name='ProductAttributeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.productattributekey')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_keys', to='store.products')),
            ],
            options={
                'unique_together': {('product', 'attribute_key')},
            },
        ),
    ]
