# Generated by Django 4.0.6 on 2024-08-11 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_productattributekey_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattributemapping',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.AddField(
            model_name='productattributemapping',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='store.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.productattributekey'),
        ),
        migrations.AlterField(
            model_name='productattributekey',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productattributemapping',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.products'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributemapping',
            unique_together={('product', 'attribute')},
        ),
        migrations.RemoveField(
            model_name='productattributemapping',
            name='attribute_key',
        ),
    ]
