# Generated by Django 4.0.6 on 2024-08-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_customer_reward_points_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/ad/images/')),
            ],
        ),
    ]
