# Generated by Django 4.0.6 on 2024-08-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
