# Generated by Django 4.0.6 on 2024-08-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.JSONField(default=list),
        ),
    ]
