# Generated by Django 4.0.6 on 2024-08-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_customer_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdImage',
        ),
    ]
