# Generated by Django 4.0.6 on 2024-08-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_order_attribute_key_order_attribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='attribute_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='attribute_value',
        ),
    ]
