name: Deploy Ecom to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3 
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Install Docker and Ensure it is Running
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          # Update the package list
          sudo apt-get update -y
          
          # Install Docker
          sudo apt-get install -y docker.io
          
          # Start and enable Docker
          sudo systemctl start docker
          sudo systemctl enable docker
          
          # Add user to Docker group (to avoid permission issues)
          sudo usermod -aG docker ubuntu
        EOF

    - name: Clone project on EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          if [ ! -d "/home/ubuntu/ecom" ]; then
            git clone https://github.com/iratusbison/ecom.git /home/ubuntu/ecom
          else
            cd /home/ubuntu/ecom
            git pull origin main
          fi
        EOF

    - name: Build and Run Docker Container
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ubuntu/ecom
          docker build -t app .
          
          # Stop and remove any existing container with the same name
          docker stop app || true
          docker rm app || true
          
          # Run the new container
          docker run -d --name app -p 8000:8000 app
        EOF

    - name: Install and Configure Nginx
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          # Install Nginx
          sudo apt-get install -y nginx
          
          # Set up Nginx reverse proxy for your subdomain
          echo "server {
              listen 80;
              server_name service.mayavisai.in;

              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
          }" | sudo tee /etc/nginx/sites-available/service.mayavisai.in
          
          # Enable the site and restart Nginx
          sudo ln -s /etc/nginx/sites-available/service.mayavisai.in /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl restart nginx
        EOF

    - name: Install Certbot and Configure SSL
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          # Install Certbot
          sudo apt-get install -y certbot python3-certbot-nginx

          # Obtain SSL certificate
          sudo certbot --nginx -d service.mayavisai.in --non-interactive --agree-tos -m your-email@example.com

          # Set up auto-renewal
          echo "0 0 * * * /usr/bin/certbot renew --quiet" | sudo tee -a /etc/crontab
        EOF
