name: Deploy Ecom to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3 
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Clone project on EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          if [ ! -d "/home/ubuntu/ecom" ]; then
            git clone https://github.com/iratusbison/ecom.git /home/ubuntu/ecom
          else
            cd /home/ubuntu/ecom
            git pull origin main
          fi
        EOF
 
    - name: Build and Run Docker Container
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ubuntu/ecom
          docker build -t app .
          docker run -d --name app -p 8000:8000 app
        EOF
