name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3 
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Copy project files to EC2
      run: |
        rsync -avz --exclude '.git' --exclude 'venv' ./ ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/ecom/

    - name: Run Docker build & deploy on EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ubuntu/ecom
          docker build -t app .
          docker run -d --name app -p 8000:8000 app
        EOF
