name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use the latest stable version

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3  # Use a valid version (v0.5.3 or latest stable)
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /path/to/your/app
          git pull origin main
          docker-compose down
          docker-compose up -d
        EOF
